//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHI_InspectionSoftware
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Inspection
    {
        public int ID { get; set; }
        [DisplayName("Address")]
        public Nullable<int> AddressID { get; set; }
        [DisplayName("Customer")]
        public Nullable<int> CustomerID { get; set; }
        [DisplayName("Inspector")]
        public Nullable<int> InspectorID { get; set; }
        [DisplayName("Realtor")]
        public Nullable<int> RealtorID { get; set; }
        [DisplayName("Inspection Date")]
        public Nullable<System.DateTime> InspectionDate { get; set; }
        [DisplayName("Status")]
        public Nullable<int> InspectionStatusID { get; set; }
        public Nullable<decimal> Price { get; set; }
        [DisplayName("Report Number")]
        public Nullable<int> InspectionReportID { get; set; }
        [DisplayName("Template")]
        public Nullable<int> TemplateID { get; set; }
    
        public virtual Address Address { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual InspectionReport InspectionReport { get; set; }
        public virtual Inspector Inspector { get; set; }
        public virtual InspectionStatus InspectionStatus { get; set; }
        public virtual Realtor Realtor { get; set; }
        public virtual Template Template { get; set; }
    }
}
