//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HHI_InspectionSoftware
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Limitation
    {
        public int ID { get; set; }
        [DisplayName("Limitation")]
        public string Name { get; set; }
        [DisplayName("System")]
        public Nullable<int> SystemID { get; set; }
        public string Description { get; set; }
        [DisplayName("Area")]
        public Nullable<int> AreaID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual HomeSystem HomeSystem { get; set; }
    }
}
